services:
  sas_devel:
    build: .
    volumes:
      - ../src:/root/sas_devel/src
    command: /bin/bash -c "
      cd /root/sas_devel
      && ls .
      && colcon build
      && source install/setup.bash"