services:
  sas_devel:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "
      cd /root/sas_devel
      && ls .
      && colcon build
      && source install/setup.bash"