services:
  sas_devel:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "
      cd /root/sas_devel/ros2_ws
      && ls .
      && colcon build
      && source install/setup.bash"